
<main>

    <section class="plans" id="plans">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="plan">
                        <img src="/app/content/site/assets/images/plans/plan-1.png" height="80px">
                        <div class="h4 mt-3">Standard</div>
                        <div class="price"><small>R$</small>14,93</div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 1 servidor</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Criação de páginas</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="plan plan-star">
                        <img src="/app/content/site/assets/images/plans/plan-2.png" height="80px">
                        <div class="h4 mt-3">Premium</div>
                        <div class="price"><small>R$</small>24,93</div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 3 servidores</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de páginas</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="plan">
                        <img src="/app/content/site/assets/images/plans/plan-3.png" height="80px">
                        <div class="h4 mt-3">Enterprise</div>
                        <div class="price"><small>R$</small>32,93<small></div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Servidores ilimitados</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de páginas</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="free-plan mb-5 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="hxl text-uppercase"><b style="color: rgb(131,58,180)">Sem dinheiro?</b> <br> <br> Não se
                        preocupe! Vamos te ajudar</div>
                </div>
                <div class="col-md-7">
                    <div class="card bg-gradient text-white px-5">
                        <div class="card-body starter-plan">
                            <div class="h1 font-weight-bold text-white text-uppercase">
                                <b style="color: #f9ca24;">Plano Starter</b> <small style="font-size: 20px;">/
                                    forever!</small>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 1 servidor
                                        </li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias
                                        </li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos
                                        </li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto
                                        </li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis
                                        </li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL
                                            grátis</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de
                                            templates</li>
                                        <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Criação de páginas
                                        </li>
                                        <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <p style="color: rgba(255,255,255,.8); font-weight: 500">
                                        Fique tranquilo! Iremos te ajudar a começar ganhar dinheiro com o seu servidor e
                                        não cobraremos até que você realmente esteja ganhando!
                                    </p>
                                    <p>
                                        É simples! Quando você atingir o limite de R$60,00 (reais) em lucro, iremos te
                                        enviar um alerta para que você altere seu plano. E se não estiver satisfeito,
                                        basta cancelar.
                                    </p>
                                </div>
                            </div>
                            <br>
                            <br>
                            <a class="btn-starter" href="https://app.steveshop.com.br/account/login">Comece a ganhar
                                dinheiro</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section id="intro" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                    <div class="section-heading">
                        <p class="lead">Nosso objetivo é administrar o site do seu servidor, deixando tudo mais prático,
                            fácil e dando a você a mobilidade que você precisa no seu site!<br>
                            Para isso, contamos com:</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5  d-none d-lg-block col-sm-12">
                    <div aos="fade-right" class="intro-img">
                        <img src="app/content/site/assets/images/resources/village-pillage/threevillagers_right.png" alt="intro-img" class="img-fluid"  width="60%">
                    </div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-12">
                    <div class="row">
                        <div class="col-lg-6 col-sm-6 col-md-6">
                            <div class="intro-box">
                                <span>01.</span>
                                <h4>Hospedagem</h4>
                                <p>Nossa hospedagem nos transmite segurança para oferecer um serviço como este. Estamos
                                    sempre online!</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6 col-md-6">
                            <div class="intro-box">
                                <span>02.</span>
                                <h4>Gerenciamento</h4>
                                <p>O gerenciamento da loja do seu servidor será feito de forma automática. Nosso sistema
                                    registra as compras e libera a ativação no servidor! </p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6 col-md-6">
                            <div class="intro-box">
                                <span>03.</span>
                                <h4>Experiência</h4>
                                <p>Nós já trabalhamos com o sistema de ativação in-game há 3 anos. Agora, além dá
                                    ativação in-game, oferecemos uma plataforma de gerenciamento e hospedagem do seu
                                    site.</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6 col-md-6">
                            <div class="intro-box">
                                <span>04.</span>
                                <h4>Decoração</h4>
                                <p>O template do seu site é grátis e você poderá alterar o nome do site, os produtos e
                                    suas descrições, valores e adicionar notícias para informar os players!</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="intro-cta">
                                <p class="lead ">Ainda tem alguma dúvida?</p>
                                <button style="--content: 'Contacto Comercial';" onclick="window.location.href='javascript:void(Tawk_API.toggle())'">
                                    <div class="left"></div>
                                    Contacto Comercial
                                    <div class="right"></div>
                                </button>

                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--
    <a href="javascript:void(Tawk_API.toggle())" class="help-item">
                                <div class="img">
                                    <img class="svg ico" src="fonts/svg/livechat.svg" height="65" alt="">
                                </div>
                                <div class="inform">
                                    <div class="title">Live Chat</div>
                                </div>
                            </a>
                            -->
    <section class="py-5 pt-2" id="features">
        <div class="container">
            <div class="h1 mb-1 text-center">Características</div>
            <div class="h5 text-muted text-center mb-4">Saiba o porquê de sermos a melhor opção para o seu servidor.
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <div class="row mt-3">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/photo-editing.png" alt="..."
                                class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Painel administrativo</div>
                            <p>Aqui você quem toma o controle da sua loja!<br> Não se preocupe, você vai deixar sua loja
                                do seu jeito.</p>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/computer.png" alt="..."
                                class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Fique online em instântes</div>
                            <p>Faça a configuração de sua nova loja em menos de 10 minutos e já comece a vender!</p>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/cloud-storage.png" alt="..."
                                class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Transações seguras</div>
                            <p>Todas as transações são feitas pelas gateways de pagamento, tornando o sistema seguro e
                                rápida.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="<?= APP_ROOT ?>app/content/site/assets/images/webstore.png" class="img-fluid" alt="...">
                </div>
            </div>
        </div>
    </section>
</main>


<!--
<div id="partner" class="wrap-container80 bg-grey">

    <div class="container">
        <div class="post-heading-center">
            <h2>Our partners</h2>
        </div>
        <div class="isotope-row animation" data-animation="animation-fade-in-up">
            <div class="item">
                <a href="https://www.minesucht.net" class="" target="_blank">
                    <img src="https://www.labymod.net/page/tpl/assets/images/partner/minesucht.png" alt="Minesucht" />
                    <p>MineSucht</p>
                </a>
            </div>
            <div class="item">
                <a href="https://teamspeak.com/?utm_source=sponsor&utm_campaign=labymedia-gmbh" class=""
                    target="_blank">
                    <img src="https://www.labymod.net/page/tpl/assets/images/partner/teamspeak.png" alt="teamspeak" class="full" />
                </a>
            </div>
            <div class="item">
                <a href="https://discordapp.com" class="" target="_blank">
                    <img src="https://www.labymod.net/page/tpl/assets/images/partner/discord.png" alt="Discord" />
                    <p>Discord</p>
                </a>
            </div>
        </div>
    </div>
</div>
-->
<!--
<div style="background-image: url(https://www.ihosts3.com/_site/img/fps.png);
         background-size: cover;" class="host-plans tab02">
        <div class="container no-padding-sm">
            <div class="row">
                <div class="part-plans">
                    <div class="col-md-5 no-padding text-xs-center text-sm-center">
                        <div class="wrap-img wrap-img-2">
                        </div>
                    </div>
                    <div class="col-md-7 no-padding-sm text-xs-center text-sm-center">
                        <div class="heading">Nosso <br><span>Servidores de Jogo</span></div>
                        <div class="subheading">Nós iremos fornecer aos vossos jogadores a melhor experiência de FPS sem Lag. Os nossos servidores são fáceis de configurar e nós temos um suporte experiente que ajudará em tudo o que precisares. </div>
                        <div class="info-group">
                            <hr style="width: 100%;border-top: 1px solid #e1393933;box-shadow: rgba(225, 57, 57, 0.37) 1px 1px 0px 1px;">
                            <span class="text"><i class="fas fa-desktop"></i> Painel de Controlo TCadmin </span>
                            <span class="text"><i class="fa fa-cog"></i> Instalação Instantânea</span>
                            <span class="text"><i class="fa fa-medkit"></i> Suporte Experiente </span>
                        </div>
                        <a href="#" class="btn"> Verifique os Planos <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
-->
<!--
<div style="background-image: url(https://www.ihosts3.com/_site/img/mine.png); background-size: cover;" class="host-plans">
    <div class="container no-padding-sm">
        <div class="row">
            <div class="part-plans">
                <div class="col-md-5 col-md-push-7 text-right text-xs-center text-sm-center">
                    <div class="wrap-img">
                    </div>
                </div>
                <div class="col-md-7 col-md-pull-5 no-padding-sm text-xs-center text-sm-center">
                    <div class="heading">Nosso <br><span>Planos Minecraft</span></div>
                    <div class="subheading">Com os nossos Planos Minecraft, tu irás poder jogar sem qualquer tipo de
                        lag. Connosco irás desfrutar do Minecraft como nunca desfrutas-te! </div>
                    <div class="info-group">
                        <hr
                            style="width: 100%;border-top: 1px solid #e1393933;box-shadow: rgba(225, 57, 57, 0.37) 1px 1px 0px 1px;">
                        <span class="text"><i class="fas fa-desktop"></i> Painel Pterodactyl </span>
                        <span class="text"><i class="fa fa-cog"></i> Activação Instantânea</span>
                        <span class="text"><i class="fa fa-medkit"></i>Suporte Experiente </span>
                    </div>
                    <a href="#" class="btn"> Verifique os Planos <i class="fa fa-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
-->
<br>
<div class="container text-center">
    <h2>Nossos Parceiros / Nossos Clientes</h2>
    <br>
    <div class="row">
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 1</p>
        </div>
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 2</p>
        </div>
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 3</p>
        </div>
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 4</p>
        </div>
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 5</p>
        </div>
        <div class="col-sm-2">
            <img src="<?= APP_ROOT ?>app/content/site/assets/images/partners/150x80.png" class="img-responsive" style="width:100%" alt="Image">
            <p>Brevemente 6</p>
        </div>
    </div>
</div><br>
<?php require_once "footer.phtml"; ?>

