<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?= $this->title ?></title>

    <link href="<?= APP_ROOT ?>app/content/site/assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/normalize/normalize.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/ionicons/ionicons.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/core.css" rel="stylesheet" type="text/css">
</head>
<body>

<?= $this->render(); ?>

<script src="<?= APP_ROOT ?>app/content/site/assets/js/jquery/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/popper/umd/popper.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/bootstrap/bootstrap.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/init.js"></script>
</body>
</html>