<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <center><h2 class="mb-1 mt-3">Gateways de pagamento</h2>
            <p class="mb-3">Configure os métodos de pagamento que sua loja irá aceitar durante uma transação. Para desativar alguma, basta não habilitar.</p></center>
        </div>
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <center><img src="https://assets.pagseguro.com.br/ps-bootstrap/ccf/img/logos/pagbank/pagbank-logo-animado_35px@3x.gif" height="50px" class="mb-4"></center>
					<center><p>Possui suporte à todos os métodos de pagamento utilizados no mercado. Seu jogador não precisa ter uma conta.</p></center>
                    <br>
                    <form method="post" class="update row">
                        <input type="hidden" name="gateway" value="pagseguro">
                        <div class="form-group col-md-6">
                            <label for="pagseguroEmail"><b>E-mail</b></label>
                            <input class="form-control" id="pagseguroEmail" name="pagseguro_EMAIL" placeholder="E-mail" value="<?= $this->gateways->data()->pagseguro_EMAIL ?>">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="pagseguroToken"><b>Token</b></label>
                            <input class="form-control" id="pagseguroToken" name="pagseguro_TOKEN" placeholder="Token" value="<?= $this->gateways->data()->pagseguro_TOKEN ?>">
                        </div>
                        <div class="form-group col-md-12">
                            <div class="form-check">
                                <label class="form-check-label text-muted">
                                    <input type="checkbox" class="form-check-input" name="show"  <?= ($this->gateways->data()->pagseguro_SHOW == 1) ? 'checked' : '' ?>> Marque para habilitar o PagSeguro
                                </label>
                            </div>
                        </div>
                        <div class="form-group m-0 col-md-12">
                            <button type="submit" class="btn btn-block btn-success">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <center><img src="https://logodownload.org/wp-content/uploads/2019/06/mercado-pago-logo.png" height="50px" class="mb-4"></center>
					<center><p>Aceite boleto, saldo em conta e cartões de crédito como métodos de pagamento. Seu jogador não precisa ter uma conta.</p></center>
                    <br>
                    <form method="post" class="update row">
                        <input type="hidden" name="gateway" value="mercadopago">
                        <div class="form-group col-md-6">
                            <label for="clientid"><b>Client ID</b></label>
                            <input class="form-control" id="clientid" name="mercadopago_ID"  value="<?= $this->gateways->data()->mercadopago_ID ?>" placeholder="Client ID">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="clientsecret"><b>Client Secret</b></label>
                            <input class="form-control" id="clientsecret" name="mercadopago_SECRET" value="<?= $this->gateways->data()->mercadopago_SECRET ?>" placeholder="Client Secret">
                        </div>
                        <div class="form-group col-md-12">
                            <div class="form-check">
                                <label class="form-check-label text-muted">
                                    <input type="checkbox" class="form-check-input" name="show" <?= ($this->gateways->data()->mercadopago_SHOW == 1) ? 'checked' : '' ?>> Marque para habilitar o MercadoPago
                                </label>
                            </div>
                        </div>
                        <div class="form-group m-0 col-md-12">
                            <button type="submit" class="btn btn-block btn-success">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <center><img src="https://logodownload.org/wp-content/uploads/2014/10/paypal-logo-3.png" height="50px" class="mb-4"></center>
					<center><p>Seus clientes poderão pagar utilizando um cartão de crédito. É necessário que seu jogador tenha uma conta no PayPal para realizar o pagamento.</p></center>
                    <br>
                    <form method="post" class="update">
                        <input type="hidden" name="gateway" value="paypal">
                        <div class="form-group">
                            <label for="paypalEmail"><b>E-mail</b></label>
                            <input class="form-control" id="paypalEmail" name="paypal_EMAIL" placeholder="E-mail do PayPal" value="<?= $this->gateways->data()->paypal_EMAIL ?>">
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label text-muted">
                                    <input type="checkbox" class="form-check-input" name="show" <?= ($this->gateways->data()->paypal_SHOW == 1) ? 'checked' : '' ?>> Marque para habilitar o PayPal
                                </label>
                            </div>
                        </div>
                        <div class="form-group m-0">
                            <button type="submit" class="btn btn-block btn-success">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $('.update').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/config/gateways/update',
                method: 'POST',
                data: $(this).serialize(),
                dataType: 'JSON',
                complete: function (response) {
                    var res = JSON.parse(response.responseText);

                    if(res.success)
                    {
                        swal({
                            type: 'success',
                            title: 'Pronto!',
                            text: res.message,
                        });
                    }else {
                        swal({
                            type: 'error',
                            title: 'Oops...',
                            text: res.message,
                        });
                    }
                }
            });

            return false;
        });
    });
</script>