<main>
    <section class="plan-section p-5" style="margin-top: -570px; position: relative; z-index: 9">
        <div class="container">
            <div style="background: #fff; border-radius: 8px; padding: 25px;">
                <div class="h1 font-weight-bold mb-5">Termos</div>
                <p>
                    A leitura e concordância com os termos de serviço e política de privacidade são condições indispensáveis para a adesão e utilização dos serviços da SteveShop. A SteveShop reserva o direito de expor sua opinião sobre qualquer serviço com ela hospedado, alterar qualquer uma ou todas as políticas, diretrizes e limitações dispostas abaixo; fique sempre atento aos termos. Nossa política de utilização é ativa e rigorosamente aplicada.
                </p>
                <div class="h4">Definição</div>
                <p>
                    Neste documento, "nós" e "nosso" refere-se a SteveShop. "Você", "cliente" e "cliente (s)" refere-se à pessoa ou pessoas responsáveis ​​pela compra e / ou pagamento de quaisquer serviços prestados pela SteveShop. Comprando na SteveShop, você concorda que você leu, concorda, e seguirá todas as regras e / ou termos deste documento. O não cumprimento destas condições irá resultar em perda de acesso sem reembolso do seu serviço/compra.
                </p>
                <div class="h4">Disputas & Reembolso</div>
                <p>
                    Após o seu serviço estar ativado, você não tem o direito de pedir reembolso, o que concedemos é o valor dentro de nosso site para gastos com outros produtos. Nós não devolvemos addons, upgrades ou fundos. Se você comprou um serviço por três meses, você vai ser capaz de obter um reembolso de metade do tempo restante de seu serviço (cobrado em dias.) Se você tiver solicitado o cancelamento do seu serviço, você não pode receber um reembolso para o seu serviço, sem exceções. Nós só podemos dar reembolsos aos serviços que estão ativos. A SteveShop tem pleno direito de suspender, cancelar ou encerrar o serviço se uma disputa está aberta. Sem exceções.
                </p>
                <div class="h4">Faturamento</div>
                <p>
                    Você é responsável pelo pagamento de sua fatura (s) no período estabelecido, se você deixar de pagar sua fatura no prazo, o serviço será suspenso, e uma taxa de 15% ao final será adicionado à sua fatura. Reservamo-nos o direito de terminar o seu serviço se você não conseguir enviar o pagamento 5 dias após a data de vencimento de sua fatura. Disputando o estorno resultará do seu serviço(s) ser cancelado sem aviso prévio. Vamos contratar uma agência de cobrança, se necessário.
                </p>
                <div class="h4">Limitação de Responsabilidade e Exclusão</div>
                <p>
                    A SteveShop, não é responsável de forma alguma pela perda de dados do seu serviço, ataques de negação de serviço ao seu serviço, ou de quaisquer atos prejudiciais para seus serviços. Nós não somos responsáveis ​​para a distribuição de informações, incluindo o do acesso não autorizado aos nossos sistemas de servidores ou qualquer outra perda de dados. A SteveShop, não deve ser responsabilizada por qualquer interrupção, atraso ou desconexão de serviços para qualquer período de tempo.
                </p>
                <div class="h4">Assinaturas PayPal</div>
                <p>
                    A SteveShop não é responsável por assinaturas no paypal que não tenham sido cancelados pelo usuário. Quaisquer pagamentos que foram feitos automaticamente não são de nossa responsabilidade e não são elegíveis para um reembolso. Então por isso, verifique sua assinatura no painel do cliente do Paypal.
                </p>
            </div>
        </div>
    </section>
</main>