version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - cdn-data:/var/www/html/cdn
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: as123as321
      MYSQL_DATABASE: steveshop
      MYSQL_USER: steveshop
      MYSQL_PASSWORD: as123as321
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8585:80"
    environment:
      PMA_HOST: db
      PMA_USER: steveshop
      PMA_PASSWORD: as123as321
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  cdn-data:
  dbdata: