<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">

<head>
    <title>SteveShop | A forma mais prática para impulsionar seu servidor.</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Faça do seu servidor uma máquina de ganhar dinheiro!">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow">

    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="SteveShop" />
    <meta property="og:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta property="og:url" content="https://www.steveshop.com.br" />
    <meta property="og:site_name" content="SteveShop" />
    <meta property="og:image" content="<?= APP_ROOT ?>/app/content/site/assets/images/logo.png" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image" content="/app/content/site/assets/images/logo.png" />
    <meta name="twitter:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta name="twitter:title" content="SteveShop" />
    <meta name="twitter:site" content="https://www.steveshop.com.br" />

    <link rel="canonical" href="https://www.steveshop.com.br" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/main.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">


    <link href='https://unpkg.com/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/button.css">
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/main.css">
    <script>
    AOS.init();
    </script>
</head>

<body>
    <section class="home-presentation">
        <div class="overlay">
            <header>
                <nav class="navbar navbar-expand-lg menu">
                    <div class="container">
                        <a class="navbar-brand" href="../">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/logo.png" alt="SteveShop" class="logo">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="/">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#plans">Planos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#features">Características</a>
                                </li>
                                <!--
                            <li class="nav-item nav-login">
                                <a class="nav-link" href="https://app.steveshop.com.br/">Entrar</a>
                            </li>
                            <li class="nav-item nav-register">
                                <a class="nav-link" href="https://app.steveshop.com.br/account/register">Registrar</a>
                            </li>
                                -->
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#pt" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="flag-icon flag-icon-pt"> </span> Portuguese
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdown09">
                                        <a class="dropdown-item" href="#en"><span class="flag-icon flag-icon-us"></span> English</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Área de Cliente
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="https://app.steveshop.com.br/account/login">Entrar</a>
                                        <a class="dropdown-item" href="https://app.steveshop.com.br/account/register">Registrar</a>
                                        <a class="dropdown-item" href="https://app.steveshop.com.br/account/recovery">Recuperar senha</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

        </div>

    </section>

    <?= $this->render(); ?>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>
    <script src="<?= APP_ROOT ?>app/content/site/assets/js/app.js"></script>
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
    var Tawk_API = Tawk_API || {},
        Tawk_LoadStart = new Date();
    (function() {
        var s1 = document.createElement("script"),
            s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5ebb2b2d967ae56c52193869/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
    </script>
    <!--End of Tawk.to Script-->

</body>


</html>