<!-- partial:index.partial.html -->
<link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" />
<a id="popuplink" href="#inline" style="display:none;"></a>
<div id="inline" style="display:none;text-align:center;">
    <img src="https://thebeachfurniture.co.nz/newbeach-logo.png" alt="" id="logo">
    <h3 style="margin-top:20px;">The Beach Furniture has changed its name to Urban & Beach Furniture</h3>
    <p>But we will continue providing the same beautifully crafted character furniture</p>
    <p><a href="javascript:;" onclick="jQuery.fancybox.close();"
            style="background-color:#333;padding:5px 10px;color:#fff;border-radius:5px;text-decoration:none;">Close</a>
    </p>
</div>
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.js"></script>
<!-- partial -->

<script src="<?= APP_ROOT ?>app/content/site/assets/js/popup2.js"></script>