<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>SteveShop | Não autorizado</title>
    <link rel="shortcut icon" href="<?= APP_ROOT ?>app/content/site/assets/images/fav.png" type="image/x-icon">

    <link href="<?= APP_ROOT ?>app/content/site/assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/normalize/normalize.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/ionicons/ionicons.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/animate/animate.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>app/content/site/assets/css/core.css" rel="stylesheet" type="text/css">
</head>
<body class="notfound">

<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto" style="min-height: 100vh">
            <div class="mid">
                <div class="error_panel">
                    <h1 class="text-center">Opss... temos um problema</h1>
                    <h4 class="text-center"><b><?= STORE_SUBDOMAIN; ?></b>!</h4>
                    <br>
                    <h6 class="text-center">Quer criar uma loja neste endereço? <a href="https://app.steveshop.com.br/account/register" class="text-danger">Clique para criar uma conta</a></h6>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="<?= APP_ROOT ?>app/content/site/assets/js/jquery/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/popper/umd/popper.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/bootstrap/bootstrap.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/wow/wow.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/init.js"></script>
</body>
</html>