<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>SteveShop | A forma mais prática para impulsionar seu servidor.</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Faça do seu servidor uma máquina de ganhar dinheiro!">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow">

    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="SteveShop" />
    <meta property="og:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta property="og:url" content="https://steveshop.com.br" />
    <meta property="og:site_name" content="SteveShop" />
    <meta property="og:image" content="<?= APP_ROOT ?>/app/content/site/assets/images/logo.png" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image" content="/app/content/site/assets/images/logo.png" />
    <meta name="twitter:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta name="twitter:title" content="SteveShop" />
    <meta name="twitter:site" content="https://steveshop.com.br" />

    <link rel="canonical" href="https://steveshop.com.br" />
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/main.css">
</head>
<body>
<section class="home-presentation">
    <div class="overlay">
        <header>
            <nav class="navbar navbar-expand-lg menu">
                <div class="container">
                    <a class="navbar-brand" href="#">
                        <img src="<?= APP_ROOT ?>app/content/site/assets/images/logo.png" alt="SteveShop" class="logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#plans">Planos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#features">Características</a>
                            </li>
                            <li class="nav-item nav-login">
                                <a class="nav-link" href="https://app.steveshop.com.br/">Entrar</a>
                            </li>
                            <li class="nav-item nav-register">
                                <a class="nav-link" href="https://app.steveshop.com.br/account/register">Registrar</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>
</section>
<?= $this->render(); ?>
<footer>

</footer>
<script src="<?= APP_ROOT ?>app/content/site/assets/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/app.js"></script>
</body>
</html>