<?php if(\app\factory\clients\ProfileFactory::isActived() == false): ?>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="alert-heading">Ei! Falta uma coisa</h5>
        <p>A confirmação do e-mail está pendente, confirme para manter a segurança da sua conta.</p>
        <hr>
        <p class="mb-0">Lembrete: Só irá receber os R$10,00 iniciais quando o e-mail for confirmado.</p>
    </div>
    <br>
<?php endif ?>
<div class="card">
    <div class="card-body p-4">
        <h3>Adicionar fundos na carteira</h3>
        <div class="divider"></div>
        <br>
        <div id="display_payment">
            <div id="display_1">
                <form method="post" id="recharge">
                    <h5>Selecione o valor de recarga</h5>
                    <div class="btn-group btn-group-lg btn-group-toggle mt-3" data-toggle="buttons">
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="20.00" autocomplete="off"> <small>R$</small>20
                        </label>
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="30.00" autocomplete="off"> <small>R$</small>30
                        </label>
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="50.00" autocomplete="off"> <small>R$</small>50
                        </label>
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="80.00" autocomplete="off"> <small>R$</small>80
                        </label>
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="100.00" autocomplete="off"> <small>R$</small>100
                        </label>
                        <label class="btn btn-light">
                            <input type="radio" name="amount" class="amount_selection" value="other" id="to_other" autocomplete="off"> Outro valor
                        </label>
                    </div>
                    <div id="other_amount" style="display: none" class="mt-3">
                        <div class="form-group">
                            <label for="other" class="m-0">Informe o valor</label>
                            <input class="form-control w-25" name="other" value="20.00" step="any" min="20.00" id="other" type="number">
                        </div>
                    </div>
                    <div class="mt-4">
                        <button class="btn btn-primary" id="to2" disabled tabindex="-1">Prosseguir...</button>
                    </div>
                </form>
            </div>
            <div id="display_2" style="display: none;">
                <h5 class="mb-3">Escolha a forma de pagamento</h5>
                <div class="row mt-4 mb-3">
                    <div class="col-md-6">
                        <button class="btn btn-light btn-lg btn-block p-3" id="toCard">
                            <img src="/app/content/painel/assets/images/icons/credit-card-2.png" style="max-width: 40px" class="img-fluid mr-3">
                            Cartão de Crédito
                        </button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-light btn-lg btn-block p-3" id="toBoleto">
                            <img src="/app/content/painel/assets/images/icons/barcode.png" style="max-width: 40px" class="img-fluid mr-3">
                            Boleto Bancário
                        </button>
                    </div>
                </div>
            </div>
            <div id="display_card" style="display: none;">
                <div class="row">
                    <div class="col-md-8">
                        <h5 class="mb-3">Informe os dados do cartão</h5>
                        <div class="alert alert-success" style="display: none"></div>
                        <div class="alert alert-danger" style="display: none"></div>
                        <div class="alert alert-info" style="display: none"></div>
                        <form class="row mt-4 mb-3" method="post" id="card_checkout">
                            <div class="form-group col-md-6">
                                <label for="fullname">Nome impresso no cartão:</label>
                                <input class="form-control" id="fullname" name="fullname" data-checkout="cardholderName">
                            </div>
                            <div class="col-md-6">
                                <label for="doc">Documento:</label>
                                <div class="row">
                                    <div class="form-group col-md-5">
                                        <select id="docType" name="docType" data-checkout="docType" class="custom-select">
                                            <option value="CPF">CPF</option>
                                            <option value="CPF">CNPJ</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-7">
                                        <input class="form-control" id="docNumber" name="docNumber">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-8">
                                <label for="cardNumber">Número do cartão:</label>
                                <input name="cardNumber" id="cardNumber" class="form-control" data-checkout="cardNumber" maxlength="16" autocomplete="off">
                                <div id="img_bandeira" style="position: absolute; top: 38px; right: 25px;"></div>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="cardCVV">CVV:</label>
                                <input name="cardCVV" id="cardCVV" data-checkout="securityCode" placeholder="123" class="form-control" maxlength="4">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="cardMonth">Mês:</label>
                                <select name="cardMonth" id="cardMonth" data-checkout="cardExpirationMonth" class="custom-select">
                                    <option value="">Selecione...</option>
                                    <?php for ($i = 1; $i <= 12; $i++) {
                                        echo "<option value='" . $i . "'>{$i}</option>";
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group col-md-3 mr-auto">
                                <label for="cardYear">Ano:</label>
                                <select name="cardYear" id="cardYear" data-checkout="cardExpirationYear" class="custom-select">
                                    <option value="">Selecione...</option>
                                    <?php for ($i = date("Y"); $i <= date("Y") + 15; $i++) {
                                        echo "<option value='" . $i . "'>{$i}</option>";
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group col-md-4 pt-2">
                                <button class="btn btn-primary btn-block mt-4">Pagar agora</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <h6 class="mb-3">Detalhes da recarga</h6>
                        <hr>
                        <p>
                            Você está recarregando R$<span id="recharge_amount">0.00</span><br> em sua carteira.
                            <br><br>
                            <small style="text-">O saldo será adicionado assim que o pagamento for aprovado</small>
                        </p>
                    </div>
                </div>
            </div>
            <div id="display_boleto" style="display: none;">
                <h5 class="mb-3">Informe seus dados</h5>
                <div class="row mt-4 mb-3">

                </div>
            </div>
        </div>
    </div>
</div>
<script src="//secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
<script>
    scripts.push(function() {

        Mercadopago.setPublishableKey("TEST-521815ad-5b88-434c-a118-ab73d19d5845");
        $(document).ready(function () {
            $("#card_checkout").validate({
                rules: {
                    fullname: {required: true},
                    docType: {required: true},
                    docNumber: {required: true},
                    cardNumber: {required: true},
                    cardMonth: {required: true},
                    cardYear: {required: true},
                    cardCVV: {required: true}
                },
                messages: {
                    fullname : "Digite o nome impresso no cartão",
                    docType: "Obrigatório",
                    docNumber: "Obrigatório.",
                    cardNumber: "Digite o número do cartão de crédito.",
                    cardMonth: "Obrigatório.",
                    cardYear: "Obrigatório.",
                    cardCVV: "Informe o CVV."
                },
                submitHandler: function () {
                    let form = document.querySelector('#card_checkout');
                    Mercadopago.createToken(form, tokenHandler);
                }
            });

            if( $("#card_checkout #cardNumber") !== ""){
                Mercadopago.getPaymentMethod({
                    "bin": getBin()
                }, setPaymentMethodInfo);
            }

            function addEvent(el, eventName, handler) {
                console.log("addEvent");
                if (el.addEventListener) {
                    el.addEventListener(eventName, handler);
                } else {
                    el.attachEvent('on' + eventName, function () {
                        handler.call(el);
                    });
                }
            };
            function tokenHandler(status, response) {
                if (status !== 200 && status !== 201) {
                    $('.alert-danger').html('Ocorreu um erro... verifique seus dados');
                } else {
                    $('.alert-danger').hide();
                    $('.alert-info').hide();

                    const form = document.querySelector('#card_checkout');
                    const card = document.createElement('input');
                    card.setAttribute('name', "token");
                    card.setAttribute('type', "hidden");
                    card.setAttribute('value', response.id);
                    form.appendChild(card);
                    doSubmit = true;

                    $('.alert-info').fadeIn('slow').html("Aguarde, estamos processando seu pagamento...");

                    let dataToSend = $('#card_checkout, #recharge').serialize();

                    $('#card_checkout [type=submit]').prop('disabled', true);

                    $.ajax({
                        url: '/account/recharge/withcard',
                        method: 'POST',
                        data: dataToSend,
                        dataType: 'JSON',
                        complete: function (response) {
                            let res = JSON.parse(response.responseText);

                            if(res.success)
                            {
                                $('.alert-info').hide();
                                $('.alert-success').fadeIn().html(res.message);

                                setTimeout(function () {
                                    location.href = res.link;
                                }, 1500);
                            }else{
                                $('.alert-info').hide();
                                $('.alert-danger').fadeIn().html(res.message);
                                $('#card_checkout [type=submit]').prop('disabled', false);
                            }
                        }
                    });
                }
            }
            function getBin() {
                const ccNumber = document.querySelector('#card_checkout input[data-checkout="cardNumber"]');
                return ccNumber.value.replace(/[ .-]/g, '').slice(0, 6);
            }
            function guessingPaymentMethod(event) {
                const bin = getBin();
                if (event.type === "keyup") {
                    if (bin.length >= 6) {
                        Mercadopago.getPaymentMethod({
                            "bin": bin
                        }, setPaymentMethodInfo);
                    }
                } else {
                    setTimeout(function () {
                        if (bin.length >= 6) {
                            Mercadopago.getPaymentMethod({
                                "bin": bin
                            }, setPaymentMethodInfo);
                        }
                    }, 100);
                }
            }
            function setPaymentMethodInfo(status, response) {
                if (status === 200) {
                    const form = document.querySelector('#card_checkout');
                    if (document.querySelector("input[name=paymentMethodId]") == null) {
                        const paymentMethod = document.createElement('input');
                        paymentMethod.setAttribute('name', "paymentMethodId");
                        paymentMethod.setAttribute('type', "hidden");
                        paymentMethod.setAttribute('value', response[0].id);
                        form.appendChild(paymentMethod);
                    } else {
                        document.querySelector("input[name=paymentMethodId]").value = response[0].id;
                    }
                    const img = "<img src='" + response[0].thumbnail.replace('http', 'https') + "'>";
                    $("#card_checkout #img_bandeira").empty();
                    $("#card_checkout #img_bandeira").append(img);

                    let val = $('.amount_selection:checked').val();
                    let amount = 0;

                    if(val === 'other')
                    {
                        let otherAmount = $('#other').val();
                        amount = parseFloat(otherAmount).toFixed(2);
                    }else{
                        amount = parseFloat(val).toFixed(2);
                    }

                    Mercadopago.getInstallments({
                        "bin": getBin(),
                        "amount": amount
                    });
                }
            }
            addEvent(document.querySelector('#card_checkout input[data-checkout="cardNumber"]'), 'keyup', guessingPaymentMethod);
            addEvent(document.querySelector('#card_checkout input[data-checkout="cardNumber"]'), 'change', guessingPaymentMethod);
        });

    });
</script>