<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SteveShop - <?= $this->title ?></title>

    <script src="https:////ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <link href="/app/content/painel/assets/auth/css/demo9/pages/login/login-1.css" rel="stylesheet" type="text/css" />
    <link href="/app/content/painel/assets/auth/vendors/global/vendors.bundle.css" rel="stylesheet" type="text/css" />
    <link href="/app/content/painel/assets/auth/css/demo9/style.bundle.css" rel="stylesheet" type="text/css" />

    <script>window.scripts = [];</script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body  class="kt-page--loading-enabled kt-page--loading kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header--minimize-menu kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--left kt-aside--fixed kt-page--loading"  >

<?= $this->render(); ?>

<script>
    var KTAppOptions = {"colors":{"state":{"brand":"#591df1","light":"#ffffff","dark":"#282a3c","primary":"#5867dd","success":"#34bfa3","info":"#36a3f7","warning":"#ffb822","danger":"#fd3995"},"base":{"label":["#c5cbe3","#a1a8c3","#3d4465","#3e4466"],"shape":["#f0f3ff","#d9dffa","#afb4d4","#646c9a"]}}};
</script>
<script src="/app/content/painel/assets/auth/vendors/global/vendors.bundle.js" type="text/javascript"></script>
<script src="/app/content/painel/assets/auth/js/demo9/scripts.bundle.js" type="text/javascript"></script>
<script>
    $(function() {
        if(scripts instanceof Array) {
            $.each(scripts, function (index, fn) {
                if(typeof fn === 'function') fn();
            });
        }
    });
</script>
</body>

</html>
