<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-1">Transações</h2>
            <p class="mb-3">Acompanhe todas transações em sua loja</p>
        </div>
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table datatable table-hover">
                            <thead>
                            <tr>
                                <th>N. Fatura</th>
                                <th>Código de Transação</th>
                                <th>Gateway</th>
                                <th class="text-center">Valor</th>
                                <th>Data e Hora</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php

                            $model = new \app\lib\Model();
                            $transactions = $model->select("SELECT * FROM `webstores_transactions` WHERE `transaction_WID`={$_SESSION['WebstoreLogged']} ORDER BY `transaction_ID` DESC", 'all');

                            foreach ($transactions as $transaction):
                            ?>
                                <tr>
                                    <td><?= $transaction->transaction_REFERENCE ?></td>
                                    <td><?= $transaction->transaction_CODE ?></td>
                                    <td><?= $transaction->transaction_GATEWAY ?></td>
                                    <td>R$ <?= number_format($transaction->transaction_GROSS_AMOUNT, 2, ',', '.') ?></td>
                                    <td><?= date('d/m/Y H:i', strtotime($transaction->transaction_DATE)) ?></td>
                                    <td><?= $transaction->transaction_PAID == 1 ? 'Pago' : 'Pendente' ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $(document).ready(function() {
            $('.datatable').DataTable();
        });
    })
</script>