<link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/popup.css">

<!-- popup -->
<div class="popScroll">
    <div class="popup">
        <span class="ribbon top-left ribbon-primary">
            <small>Aviso Prévio!</small>
        </span>
        <h1>Inscrição na Newsletter</h1>
        <div class="subscribe-widget">
            <!-- form -->
            <form id="subscribe-form">
                <input type="email" name="email" placeholder="Seu email por favor" class="email-form" required>
                <br>   <br>
                <button type="submit" class="button">Subscrever</button>
            </form>
            <!-- end form-->
        </div>
        <p>Estamos fazer uma manutenção no site, Vamos trazer mais novidades. Algumas das funções no site vão estar inativas durante a mantenção</p>
        <div id="option">
            <img src="https://www.hostinger.com.br/tutoriais/wp-content/uploads/sites/12/2018/04/Como-Criar-um-Server-de-Minecraft-1.png"
                class="img-responsive" style="width:100%" alt="Image">

        </div>
    </div>
</div>

<script src="<?= APP_ROOT ?>app/content/site/assets/js/popup.js"></script>