<main>
    <section class="plans" id="plans">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="plan">
                        <img src="/app/content/site/assets/images/plans/plan-1.png" height="80px">
                        <div class="h4 mt-3">Standard</div>
                        <div class="price"><small>R$</small>14,93</div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 1 servidor</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Criação de páginas</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="plan plan-star">
                        <img src="/app/content/site/assets/images/plans/plan-2.png" height="80px">
                        <div class="h4 mt-3">Premium</div>
                        <div class="price"><small>R$</small>24,93</div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 3 servidores</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de páginas</li>
                            <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="plan">
                        <img src="/app/content/site/assets/images/plans/plan-3.png" height="80px">
                        <div class="h4 mt-3">Enterprise</div>
                        <div class="price"><small>R$</small>32,93<small></div>
                        <hr>
                        <p>Sem limite de ganhos mensais</p>
                        <ul>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Servidores ilimitados</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de páginas</li>
                            <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Domínio próprio</li>
                        </ul>
                        <a href="https://app.steveshop.com.br/account/login">Contratar agora</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="free-plan mb-5 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="hxl text-uppercase"><b style="color: rgb(131,58,180)">Sem dinheiro?</b> <br> <br> Não se preocupe! Vamos te ajudar</div>
                </div>
                <div class="col-md-7">
                    <div class="card bg-gradient text-white px-5">
                        <div class="card-body starter-plan">
                            <div class="h1 font-weight-bold text-white text-uppercase">
                                <b style="color: #f9ca24;">Plano Starter</b> <small style="font-size: 20px;">/ forever!</small>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Apenas 1 servidor</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de categorias</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Criação de produtos</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Cupons de desconto</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Subdomínio grátis</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Certificado SSL grátis</li>
                                        <li><i class="fa fa-check mr-2" style="color: #3ECF8E"></i>Customização de templates</li>
                                        <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Criação de páginas</li>
                                        <li><i class="fa fa-times mr-2" style="color: #ff5555"></i>Domínio próprio</li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <p style="color: rgba(255,255,255,.8); font-weight: 500">
                                        Fique tranquilo! Iremos te ajudar a começar ganhar dinheiro com o seu servidor e não cobraremos até que você realmente esteja ganhando!
                                    </p>
                                    <p>
                                        É simples! Quando você atingir o limite de R$60,00 (reais) em lucro, iremos te enviar um alerta para que você altere seu plano. E se não estiver satisfeito, basta cancelar.
                                    </p>
                                </div>
                            </div>
                            <br>
                            <br>
                            <a class="btn-starter" href="https://app.steveshop.com.br/account/login">Comece a ganhar dinheiro</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="py-5 pt-2 bg-white" id="features">
        <div class="container">
            <div class="h1 mb-1 text-center">Características</div>
            <div class="h5 text-muted text-center mb-4">Saiba o porquê de sermos a melhor opção para o seu servidor.</div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <div class="row mt-3">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/photo-editing.png" alt="..." class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Painel administrativo</div>
                            <p>Aqui você quem toma o controle da sua loja!<br> Não se preocupe, você vai deixar sua loja do seu jeito.</p>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/computer.png" alt="..." class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Fique online em instântes</div>
                            <p>Faça a configuração de sua nova loja em menos de 10 minutos e já comece a vender!</p>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-2">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/icons/cloud-storage.png" alt="..." class="img-fluid">
                        </div>
                        <div class="col-10">
                            <div class="h4">Transações seguras</div>
                            <p>Todas as transações são feitas pelas gateways de pagamento, tornando o sistema seguro e rápida.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="<?= APP_ROOT ?>app/content/site/assets/images/webstore.jpg" class="img-fluid" alt="...">
                </div>
            </div>
        </div>
    </section>
</main>
<footer class="py-5 text-white" style="background: #212121">
    <div class="container">
        <img src="/app/content/site/assets/images/logo.png" height="36" class="mb-2">
        <p class="m-0 text-muted">&copy; SteveShop. Todos direitos reservados</p>
    </div>
</footer>