<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SteveShop IDE</title>

    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="/app/content/editor/assets/js/codemirror/theme/dracula.css">
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/scroll/simplescrollbars.css">
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/hint/show-hint.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="/app/content/editor/assets/css/main.css">
    <script>window.scripts = [];</script>
</head>
<body class="ide">
<?= $this->render() ?>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/lib/codemirror.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/fold/xml-fold.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/mode/xml/xml.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/mode/javascript/javascript.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/mode/css/css.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/edit/closetag.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/mode/markdown/markdown.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/scroll/simplescrollbars.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/hint/show-hint.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/hint/xml-hint.js"></script>
<script src="<?= APP_ROOT ?>app/content/editor/assets/js/codemirror/addon/hint/html-hint.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script src="/app/content/editor/assets/js/app.js"></script>
<script>
    $(function() {
        if(scripts instanceof Array) {
            $.each(scripts, function (index, fn) {
                if(typeof fn === 'function') fn();
            });
        }
    });
</script>
</body>
</html>