<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Painel de Controle</title>

    <link href="<?= APP_ROOT ?>/app/content/admin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/app/content/admin/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>/app/content/admin/assets/css/sb-admin.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131772064-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-131772064-1');
    </script>

    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="77c381e7-c013-465b-adf7-ba4d49c8237f";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
</head>
<body class="bg-dark">

<?= $this->render(); ?>

<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/jquery/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/javascript/functions.js"></script>
</body>

</html>