<div class="card-auth">
    <img src="https://app.steveshop.com.br/app/content/site/assets/images/logo.png" class="logo" alt="...">
    <div class="card-content">
        <form method="post" id="auth" autocomplete="off">
            <div class="alert">Acesso não autorizado</div>
            <p style="margin-bottom: 8px; margin-top: 0;">Código de acesso:</p>
            <input class="input-control" name="code" placeholder="Seu código de acesso" autocomplete="off">
            <button class="input-btn">Acessar</button>
        </form>
    </div>
</div>
<script>
    scripts.push(function () {

        $('#auth').on('submit', function (e) {
            e.preventDefault();

            $('.alert').hide();

            $.ajax({
                url: '/login/auth',
                method: 'POST',
                data: $(this).serialize(),
                dataType: 'json',
                complete: function (data) {

                    var res = JSON.parse(data.responseText);

                    if(res.success) {
                        return location.href = '/';
                    }

                    $('.alert').fadeIn().html(res.message);
                }
            });

            return false;
        });
    });
</script>