<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>SteveShop | Loja não encontrada</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Faça do seu servidor uma máquina de ganhar dinheiro!">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow">

    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="CashMarket" />
    <meta property="og:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta property="og:url" content="https://cashmarket.com.br" />
    <meta property="og:site_name" content="CashMarket" />
    <meta property="og:image" content="<?= APP_ROOT ?>/app/content/site/assets/images/logo.png" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image" content="/app/content/site/assets/images/logo.png" />
    <meta name="twitter:description" content="Faça do seu servidor uma máquina de ganhar dinheiro!" />
    <meta name="twitter:title" content="CashMarket" />
    <meta name="twitter:site" content="https://cashmarket.com.br" />

    <link rel="canonical" href="https://cashmarket.com.br" />
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/main.css">
</head>
<body class="error">
<main>
    <div class="container">
        <div class="row" style="margin-top: 22vh;">
            <div class="col-md-6 mx-auto">
                <div class="night">
                    <span class="moon"></span>
                    <span class="spot1"></span>
                    <span class="spot2"></span>
                    <ul>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <h1 class="font-weight-bold text-right mt--50 mb-4" style="font-size: 58px; line-height: 54px;">Loja não encontrada</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="font-weight-bold mt-3">
                            A loja "<b><?= STORE_SUBDOMAIN; ?></b>" não foi encontrada, é possível que nunca existiu.
                        </div>
                    </div>
                    <div class="col-md-5 pt-4">
                        <a href="https://steveshop.com.br/" style="background: rgba(113, 89, 193, 1); padding: 13px 25px; color: #FFF; border-radius: 8px; font-weight: 600;">Voltar a SteveShop</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</main>
<script src="<?= APP_ROOT ?>app/content/site/assets/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?= APP_ROOT ?>app/content/site/assets/js/app.js"></script>
</body>
</html>