<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-1">Categorias</h2>
            <p class="mb-3">Gerencie as categorias da loj</p>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4>Adicionar categorias</h4>
                    <br>
                    <form method="post" id="register">
                        <div class="form-group row">
                            <label for="inp1" class="col-sm-2 col-form-label">Categoria</label>
                            <div class="col-sm-10">
                                <input class="form-control" id="inp1" name="name" placeholder="Nome do servidor">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inp2" class="col-sm-2 col-form-label">Servidor</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="inp2" name="server">
                                    <?php

                                        $servers = $this->server->row();
                                        foreach ($servers as $server):
                                    ?>
                                    <option value="<?= $server->server_ID ?>"><?= $server->server_NAME ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-2 col-form-label">Mostrar</div>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <label class="form-check-label text-muted">
                                        <input type="checkbox" class="form-check-input" name="show" checked>
                                        Mostrar no site
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group m-0 row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-success">Adicionar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <h4>Categorias</h4>
                    <br>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">ID #</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Servidor</th>
                            <th scope="col">Mostrar</th>
                            <th scope="col">Deletar</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php

                        $categories = $this->categories->row();

                        if($this->categories->rows($_SESSION['WebstoreLogged']) == 0)
                        {
                            echo "<tr><th colspan='5'>Não há categorias</th></tr>";
                        }

                        foreach ($categories as $category):
                            ?>
                            <tr>
                                <th scope="row"><?= $category->category_ID ?></th>
                                <td>
                                    <form method="post" class="att">
                                        <input type="hidden" name="id" value="<?= $category->category_ID ?>">
                                        <input class="form-control form-control-sm" name="name" value="<?= $category->category_NAME ?>">
                                    </form>
                                </td>
                                <td>
                                    <?= $this->server->name($category->category_SID) ?>
                                </td>
                                <td>
                                    <div class="form-check">
                                        <label class="form-check-label text-muted">
                                            <input type="checkbox" class="form-check-input switch-show" id="<?= $category->category_ID ?>" name="show" <?= $category->category_SHOW == 1 ? 'checked' : '' ?>>
                                            Mostrar no site
                                        </label>
                                    </div>
                                </td>
                                <td><button class="btn btn-danger btn-sm delete" id="<?= $category->category_ID ?>">Deletar</button></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $('#register').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/webstore/categories/add',
                method: 'POST',
                data: $(this).serialize(),
                dataType: 'JSON',
                complete: function (response) {
                    var res = JSON.parse(response.responseText);

                    if(res.success)
                    {
                        Swal.fire({
                            type: 'success',
                            title: 'Pronto!',
                            text: res.message,
                        });
                        setTimeout(function () {
                            location.reload();
                        }, 2500);
                    }else {
                        Swal.fire({
                            type: 'error',
                            title: 'Oops...',
                            text: res.message,
                        });
                    }
                }
            });

            return false;
        });

        $('.delete').on('click', function (e) {

            e.preventDefault();

            $.ajax({
                url: '/webstore/categories/delete',
                method: 'POST',
                data: { id: $(this).attr('id') },
                complete: function () {
                    location.reload();
                }
            });

            return false;

        });

        $('.switch-show').on('click', function (e) {

            var set = $(this).is(':checked') ? 'on' : 'off';
            let id = $(this).attr('id');

            $.ajax({
                url: '/webstore/categories/show',
                method: 'POST',
                data: { id: id, mode: set },
                complete: function () {

                }
            })

        });

        $('.att').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/webstore/categories/update',
                method: 'POST',
                data: $(this).serialize(),
                complete: function () {

                }
            });

            return false;
        });
    });
</script>