<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-1">Integração do Plugin</h2>
            <p class="mb-3">Conecte seu servidor a sua loja. É simples!</p>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body p-5">
					<h3>Como integro meu servidor a minha loja?</h3>
					<p>Para integrar seu serivdor em nosso sistema é muito fácil, basta você seguir os passos abaixo que estará configurado perfeitamente!</p>
					<hr>
                    <h5><span class="ml-2">Para darmos inicio a configuração do plugin do <b>STEVESHOP</b> você precisa realizar o download no botão logo abaixo.</span></h5>
					<p><small>Clique no botão para realizar o download de plugin.</small></p>
                    <a href="/cdn/SteveShop.jar" class="btn" style="background: #7358C1; padding: 8px; color: #FFF; border-radius: 5px;" download><i class="fa fa-download mr-1"></i> BAIXAR PLUGIN</a>
					<br>
					<br>
					<h5><span class="ml-2">Acesse o FTP (Filezilla) da sua hospedagem minecraft, vá na pasta plugins e adicione o plugin <b>SteveShop.jar</b> dentro da pasta, logo após ter colocado, reinicie o servidor para que o plugin gere as pastas e seus arquivos.</span></h5>
					<hr>
                    <h5><span class="ml-2">Após ter enviado o plugin para o servidor e gerado a pasta com os arquivos, utilize o comando abaixo para definir o token da loja.</span></h5>
                    <input class="form-control bg-light w-50" readonly value="/cm token <?= $this->webstore->token() ?>">
					<p><small>Utilize para manda o plugin funcionar apenas para sua loja.</p></small>
                    <h5><span class="ml-2">Depois de ter executado o comando acima defina em qual servidor o plugin enviará os pacotes criados.</span></h5>
                    <input class="form-control bg-light w-50" readonly value="/cm server :server">
                    <p><small class="text-muted">Esse <b>:server</b> é o <b>ID</b> do servidor, gerado quando cria o servidor<br>caso não tenha criado ainda <a href="https://app.cashmarket.com.br/webstore/servers">clique aqui</a> para criar.</small></p>
                    <br><br>
                    <h5 class="m-0">Pronto, agora você pode iniciar suas vendas em sua loja!</h5>
					<br>
					<p>Versão do plugin: <span style="background: #7358C1; padding: 2px; color: #FFF; border-radius: 5px;"><b>1.0-BETA</b></span></p>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $('.update').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/config/gateways/update',
                method: 'POST',
                data: $(this).serialize(),
                dataType: 'JSON',
                complete: function (response) {
                    var res = JSON.parse(response.responseText);

                    if(res.success)
                    {
                        swal({
                            type: 'success',
                            title: 'Pronto!',
                            text: res.message,
                        });
                    }else {
                        swal({
                            type: 'error',
                            title: 'Oops...',
                            text: res.message,
                        });
                    }
                }
            });

            return false;
        });
    });
</script>