<link rel="stylesheet" href="<?= APP_ROOT ?>app/content/site/assets/css/footer.css">
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <a class="navbar-brand" href="../">
                        <img src="<?= APP_ROOT ?>app/content/site/assets/images/logo.png" alt="SteveShop" class="logo-footer">
                    </a>
                    <p> Gerar receita a partir do seu servidor minecraft, 
                        nós sjudamos os vossos servidores a ganhar mais dinheiro ser usando nossa plataforma de monetização.
                    </p>
                    <p>
                        <i class="fas fa-code"></i> com<i class="fas fa-heart"></i> por 
                        <a href="#" target="_blank">
                            <img src="<?= APP_ROOT ?>app/content/site/assets/images/webdev-BrunoRibeiro-logo.png" class="logo-footer-dev" width="113" height="28">
                        </a>
                    </p>
                    <p>
                        <strong>Email:</strong> geral@steveshop.com.br<br>
                    </p>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Links Úteis</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>about/">Sobre nós</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>affiliate/">Programa de afiliados</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>legal/payments">Pagamentos</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>legal/refund">Reembolso</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>legal/tos">Termos de serviço</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>legal/privacy">Política de Privacidade</a></li>
                        
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Suporte / Apoio</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>support/">Base de conhecimento</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>#">Enviar Ticket</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>changelog/">Changelog</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>special-offers/refer-a-friend">Convidar um Amigo</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="<?= APP_ROOT ?>partners/">Programa de parceiros</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Inscrição na Newsletter</h4>
                    <p>Quer ser o primeiro a saber a nossas novidades e promoções?</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="container">

        <div class="copyright-wrap d-md-flex py-4">
            <div class="mr-md-auto text-center text-md-left">
                <div class="copyright">
                &copy; 2019-<?php echo date("Y"); ?> <strong><span>SteveShop</span></strong>. Todos os direitos reservados a <a href="#" style="color: white" target="_blank">Steveshop</a>
                </div>
                <div class="credits">
                    Projetado por <a href="#">Bruno Ribeiro</a>
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="github"><i class="bx bxl-github"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="https://discord.gg/Vzj5eWu" class="discord"><i class="bx bxl-discord"></i></a>
            </div>
        </div>

    </div>
</footer>
