<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-1">Servidores</h2>
            <p class="mb-3">Gerenciar servidores</p>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h4>Adicionar servidor</h4>
                    <br>
                    <form method="post" id="register">
                        <div class="form-group row">
                            <label for="inp1" class="col-sm-2 col-form-label">Servidor</label>
                            <div class="col-sm-10">
                                <input class="form-control" id="inp1" name="name" placeholder="Nome do servidor">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-2">Mostrar</div>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <label class="form-check-label text-muted">
                                        <input type="checkbox" class="form-check-input" name="show" checked>
                                        Mostrar no site
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group m-0 row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-success">Adicionar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <h4>Servidores</h4>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">ID #</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Mostrar</th>
                                <th scope="col">Deletar</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php

                                $servers = $this->server->row();

                                if($this->server->counter($_SESSION['WebstoreLogged']) == 0)
                                {
                                    echo "<tr><th colspan='4'>Não há servidores</th></tr>";
                                }

                                foreach ($servers as $server):
                            ?>
                            <tr>
                                <th scope="row"><?= $server->server_ID ?></th>
                                <td>
                                    <form method="post" class="att">
                                        <input type="hidden" name="id" value="<?= $server->server_ID ?>">
                                        <input class="form-control form-control-sm" name="name" value="<?= $server->server_NAME ?>">
                                    </form>
                                </td>
                                <td>
                                    <div class="form-check">
                                        <label class="form-check-label text-muted">
                                            <input type="checkbox" class="form-check-input switch-show" id="<?= $server->server_ID ?>" name="show" <?= $server->server_SHOW == 1 ? 'checked' : '' ?>>
                                            Mostrar no site
                                        </label>
                                    </div>
                                </td>
                                <td><button class="btn btn-danger btn-sm delete" id="<?= $server->server_ID ?>">Deletar</button></td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $('#register').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/webstore/servers/add',
                method: 'POST',
                data: $(this).serialize(),
                dataType: 'JSON',
                complete: function (response) {
                    var res = JSON.parse(response.responseText);

                    if(res.success)
                    {
                        Swal.fire({
                            type: 'success',
                            title: 'Pronto!',
                            text: res.message,
                        });
                        setTimeout(function () {
                            location.reload();
                        }, 2500);
                    }else {
                        Swal.fire({
                            type: 'error',
                            title: 'Oops...',
                            text: res.message,
                        });
                    }
                }
            });

            return false;
        });

        $('.delete').on('click', function (e) {

            e.preventDefault();

            $.ajax({
                url: '/webstore/servers/delete',
                method: 'POST',
                data: { id: $(this).attr('id') },
                complete: function () {
                    location.reload();
                }
            });

            return false;

        });

        $('.switch-show').on('click', function (e) {

            var set = $(this).is(':checked') ? 'on' : 'off';
            let id = $(this).attr('id');

            $.ajax({
                url: '/webstore/servers/show',
                method: 'POST',
                data: { id: id, mode: set },
                complete: function () {

                }
            })

        });

        $('.att').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: '/webstore/servers/update',
                method: 'POST',
                data: $(this).serialize(),
                complete: function () {

                }
            });

            return false;
        })
    });
</script>