<?php

$plan[1] = 'Starter';
$plan[2] = 'Standard';
$plan[3] = 'Premium';
$plan[4] = 'Enterprise';
?>
<div class="content-wrapper">
    <h2 class="mb-1">Minhas Lojas</h2>
    <p class="mb-3">Gerencie sua lojas</p>
    <div class="row">
        <?php foreach ($this->webstores->listAll() as $webstore): ?>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="h4 m-0 mt-2 text-dark">
                        <?= $webstore->webstore_ID_NAME ?>
                        <a href="https://<?= $webstore->webstore_SUBDOMAIN ?>.steveshop.com.br" class="float-right h6 font-weight-light" target="_blank"><?= $webstore->webstore_SUBDOMAIN ?>.steveshop.com.br</a>
                    </div>
                    <p class="mt-3">
                        <span class="text-muted">
                            MINECRAFT<br>
                            ID: <?= $webstore->webstore_ID ?> <br>
                            Plano: <?= $plan[$webstore->webstore_PLAN] ?>
                        </span>
                    </p>
                    <br>
                    <?php if($_SESSION['WebstoreLogged'] != $webstore->webstore_ID): ?>
                    <button class="text-uppercase btn btn-primary login" id="<?= $webstore->webstore_ID ?>">Logar</button>
                    <?php else: ?>
                    <button class="text-uppercase btn btn-primary" disabled tabindex="-1">Logado</button>
                    <?php endif; ?>
                    <?php if($webstore->webstore_PLAN != 1): ?>
                        <button class="text-uppercase btn btn-success">Renovar</button>
                    <?php endif; ?>
                    <button class="text-uppercase btn btn-danger delete" id="<?= $webstore->webstore_ID ?>">Deletar</button>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="col-md-6">
            <br>
            <a href="/webstores/create" class="text-decoration-none">
                <div class="card" style="border: dashed 2px #eee;">
                    <div class="card-body pt-5 pb-5">
                        <div class="h1 text-center text-muted"><i class="far fa-plus-square"></i></div>
                        <div class="h3 text-center text-muted">Criar uma loja</div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<script>
    scripts.push(function () {
        $('.delete').on('click', function () {

            var r = confirm("Você tem certeza disto?");
            if (r === true) {
                $.ajax({
                    url: '/webstores/actions/delete',
                    method: 'POST',
                    data: { id: $(this).attr('id') },
                    complete: function () {
                        location.reload();
                    }
                })
            }
        });
    })
</script>
